- name: yum install packages
  yum: name={{ item }} state=installed
  tags:
    - INSTALL
  with_items:
    - libselinux-python
    - vim
    - man
    - patch
    - make
    - cmake
    - gcc
    - gcc-c++
    - flex
    - bison
    - file
    - libtool
    - libtool-libs
    - autoconf
    - kernel-devel
    - libjpeg
    - libjpeg-devel
    - libpng
    - libpng-devel
    - libpng10
    - libpng10-devel
    - gd
    - gd-devel
    - freetype
    - freetype-devel
    - libxml2
    - libxml2-devel
    - zlib
    - zlib-devel
    - glib2
    - glib2-devel
    - bzip2
    - bzip2-devel
    - libevent
    - libevent-devel
    - ncurses
    - ncurses-devel
    - curl
    - curl-devel
    - e2fsprogs
    - e2fsprogs-devel
    - krb5-devel
    - libidn
    - libidn-devel
    - openssl
    - openssl-devel
    - vim-minimal
    - gettext
    - gettext-devel
    - ncurses-devel
    - gmp-devel
    - unzip
    - libcap
    - libxslt
    - enchant
    - enchant-devel
    - libmcrypt
    - mhash
    - mcrypt
    - libmcrypt-devel
    - mhash-devel
    - aspell-devel
