- name: create directory webserver
  file:
    path: /data/webserver
    state: directory

- name: create directory www
  file:
    path: /data/www
    state: directory

- name: create directory program
  file:
    path: /data/program/{{ServerName}}
    state: directory

- name: copy tomcat
  copy:
    src: "{{tomcat}}"
    dest: /data/webserver/

- name: uncompress tomcat
  raw: tar zxf /data/webserver/{{tomcat}} -C /data/webserver

- name: copy test code
  copy:
    src: index.jsp
    dest: /data/www/{{ServerName}}/ROOT/

- name: change tomcat name
  command: mv /data/webserver/{{tomcat}} /data/webserver/{{ServerName}}

- name: change shutdown port
  lineinfile:
    dest: /data/webserver/{{ServerName}}/conf/server.xml
    state: present
    regexp: '<Server port'
    line: '<Server port="{{ShutdownPort}}" shutdown="SHUTDOWN">'

- name: change http port
  lineinfile:
    dest: /data/webserver/{{ServerName}}/conf/server.xml
    state: present
    regexp: '<Connector port="8080"'
    line: '<Connector port="{{HttpPort}}" protocol="HTTP/1.1"'

- name: change ajp port
  lineinfile:
    dest: /data/webserver/{{ServerName}}/conf/server.xml
    state: present
    regexp: '<Connector port="8009"'
    line: '<Connector port="{{AjpPort}}" protocol="AJP/1.3" redirectPort="8443" />'

- name: change server name
  lineinfile:
    dest: /data/webserver/{{ServerName}}/conf/server.xml
    state: present
    regexp: '<Host name'
    line: '<Host name="localhost"  appBase="/data/www/{{ServerName}}"'
