---
- hosts: "{{ hosts }}"
  gather_facts: false
 
  vars:
    profile:
      - "export NODE_HOME=/usr/local/node"
      - "export PATH=$PATH:$NODE_HOME/bin"
      - "export NODE_ENV=master" 

  roles:
    - role: node
