- name: create path webserver
  file:
    path: /data/webserver
    state: directory

- name: copy libmemcached file
  copy:
    src: libmemcached-1.0.4.tar.gz
    dest: /data/webserver/

- name: unarchive libmemcached file
  unarchive:
    src: /data/webserver/libmemcached-1.0.4.tar.gz
    dest: /data/webserver
    copy: no

- name: install libmemcached
  shell: cd /data/webserver/libmemcached-1.0.4 && ./configure --prefix=/usr/local/libmemcached && make -j 8 && make install && cd .. && rm -rf libmemcached-1.0.4*
